In [1]:
import torch
from utils import read_from_jsonl
from utils import DataLoader
import matplotlib.pyplot as plt
train_data = read_from_jsonl("train.jsonl")
test_data = read_from_jsonl("test.jsonl")

train_data_loader = DataLoader(train_data[:2000], batch_size=len(train_data[:2000]))
test_data_loader = DataLoader(test_data, batch_size=1)

In [2]:
from utils import RecurrentPerceptron

a = RecurrentPerceptron(clip_grads=True, clip=1., verbose=False)
# a.train_from_dataloader(train_data_loader, lr=0.05, nepochs=500, debug=False, print_interval=50)
a.load_model('model.pkl')

In [3]:
a.W, a.V

(tensor([ 21.9425,  12.3735,  10.4288,  11.9462,  15.9650, -14.3887, -10.7598,
         -14.0571, -10.5215]),
 tensor(-0.6757))

In [4]:
a.test_from_dataloader(test_data_loader, verbose=True)

  0%|          | 0/3453 [00:00<?, ?it/s]

tensor(0.8423)

In [40]:
from tqdm.notebook import tqdm

# num_cor = 0
# total = 0
num = 0
incor_instances = []
ops = []
for d in tqdm(test_data_loader, disable=True) :
    if num>20 : break 
    for b in d:
        x = b["pos_tags"]
        y = b["chunk_tags"]
        op = a.infer(x)
        if not torch.equal(op, torch.tensor(y)) : 
            print(f'{y=}')
            print(f'{op=}')
            num += 1
            incor_instances.append(b)
            ops.append(op)
        # num_cor += sum(torch.tensor(y)==op)
        # total += len(y)

y=array([1, 1, 1, 0, 0, 0])
op=tensor([1, 1, 1, 0, 0, 1])
y=array([1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1])
op=tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        1])
y=array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1])
op=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1])
y=array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1])
op=tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1])
y=array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1])
op=tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])
y=array([1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])
op=tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1

In [26]:
len(incor_instances)

11

In [27]:
incor_instances[0], ops[0]

({'tokens': ['AL-AIN', ',', 'United', 'Arab', 'Emirates', '1996-12-06'],
  'chunk_tags': array([1, 1, 1, 0, 0, 0]),
  'pos_tags': array([[1, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 1, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 1, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 1]])},
 tensor([1, 1, 1, 0, 0, 1]))

In [29]:
ins = 1
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Japan', 'began', 'the', 'defence', 'of', 'their', 'Asian', 'Cup', 'title', 'with', 'a', 'lucky', '2-1', 'win', 'against', 'Syria', 'in', 'a', 'Group', 'C', 'championship', 'match', 'on', 'Friday', '.']
[1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 1 1 1]
tensor([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
        1])


In [30]:
ins = 2
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['But', 'China', 'saw', 'their', 'luck', 'desert', 'them', 'in', 'the', 'second', 'match', 'of', 'the', 'group', ',', 'crashing', 'to', 'a', 'surprise', '2-0', 'defeat', 'to', 'newcomers', 'Uzbekistan', '.']
[1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1]
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
        1])


In [31]:
ins = 3
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['China', 'controlled', 'most', 'of', 'the', 'match', 'and', 'saw', 'several', 'chances', 'missed', 'until', 'the', '78th', 'minute', 'when', 'Uzbek', 'striker', 'Igor', 'Shkvyrin', 'took', 'advantage', 'of', 'a', 'misdirected', 'defensive', 'header', 'to', 'lob', 'the', 'ball', 'over', 'the', 'advancing', 'Chinese', 'keeper', 'and', 'into', 'an', 'empty', 'net', '.']
[1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1 0 0 0 1
 1 1 0 0 1]
tensor([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1])


In [32]:
ins = 4
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Oleg', 'Shatskiku', 'made', 'sure', 'of', 'the', 'win', 'in', 'injury', 'time', ',', 'hitting', 'an', 'unstoppable', 'left', 'foot', 'shot', 'from', 'just', 'outside', 'the', 'area', '.']
[1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 0 1]
tensor([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1])


In [33]:
ins = 5
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Despite', 'winning', 'the', 'Asian', 'Games', 'title', 'two', 'years', 'ago', ',', 'Uzbekistan', 'are', 'in', 'the', 'finals', 'as', 'outsiders', '.']
[1 1 1 0 0 0 1 0 1 1 1 1 1 1 0 1 1 1]
tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [34]:
ins = 6
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Two', 'goals', 'from', 'defensive', 'errors', 'in', 'the', 'last', 'six', 'minutes', 'allowed', 'Japan', 'to', 'come', 'from', 'behind', 'and', 'collect', 'all', 'three', 'points', 'from', 'their', 'opening', 'meeting', 'against', 'Syria', '.']
[1 0 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1]
tensor([1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 1, 1])


In [35]:
ins = 7
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Takuya', 'Takagi', 'scored', 'the', 'winner', 'in', 'the', '88th', 'minute', ',', 'rising', 'to', 'head', 'a', 'Hiroshige', 'Yanagimoto', 'cross', 'towards', 'the', 'Syrian', 'goal', 'which', 'goalkeeper', 'Salem', 'Bitar', 'appeared', 'to', 'have', 'covered', 'but', 'then', 'allowed', 'to', 'slip', 'into', 'the', 'net', '.']
[1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 1]
tensor([1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1])


In [36]:
ins = 8
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['It', 'was', 'the', 'second', 'costly', 'blunder', 'by', 'Syria', 'in', 'four', 'minutes', '.']
[1 1 1 0 0 0 1 1 1 1 0 1]
tensor([1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1])


In [37]:
ins = 9
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Defender', 'Hassan', 'Abbas', 'rose', 'to', 'intercept', 'a', 'long', 'ball', 'into', 'the', 'area', 'in', 'the', '84th', 'minute', 'but', 'only', 'managed', 'to', 'divert', 'it', 'into', 'the', 'top', 'corner', 'of', 'Bitar', "'s", 'goal', '.']
[1 0 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 0 1]
tensor([1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 1])


In [38]:
ins = 10
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Japan', 'coach', 'Shu', 'Kamo', 'said', ':', "'", "'", 'The', 'Syrian', 'own', 'goal', 'proved', 'lucky', 'for', 'us', '.']
[1 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 1]
tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1])


In [41]:
ins = 11
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['The', 'Syrians', 'scored', 'early', 'and', 'then', 'played', 'defensively', 'and', 'adopted', 'long', 'balls', 'which', 'made', 'it', 'hard', 'for', 'us', '.', "'"]
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


In [42]:
ins = 12
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Japan', ',', 'co-hosts', 'of', 'the', 'World', 'Cup', 'in', '2002', 'and', 'ranked', '20th', 'in', 'the', 'world', 'by', 'FIFA', ',', 'are', 'favourites', 'to', 'regain', 'their', 'title', 'here', '.']
[1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1]
tensor([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])


In [43]:
ins = 13
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['All', 'four', 'teams', 'are', 'level', 'with', 'one', 'point', 'each', 'from', 'one', 'game', '.']
[1 0 0 1 1 1 1 0 1 1 1 0 1]
tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [44]:
ins = 14
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['ROME', '1996-12-06']
[1 0]
tensor([1, 1])


In [45]:
ins = 15
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['on', 'Friday', 'for', 'their', 'friendly', 'against', 'Scotland', 'at', 'Murrayfield', 'more', 'than', 'a', 'year', 'after', 'the', '30-year-old', 'wing', 'announced', 'he', 'was', 'retiring', 'following', 'differences', 'over', 'selection', '.']
[1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1]
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1])


In [46]:
ins = 16
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Cuttitta', ',', 'who', 'trainer', 'George', 'Coste', 'said', 'was', 'certain', 'to', 'play', 'on', 'Saturday', 'week', ',', 'was', 'named', 'in', 'a', '21-man', 'squad', 'lacking', 'only', 'two', 'of', 'the', 'team', 'beaten', '54-21', 'by', 'England', 'at', 'Twickenham', 'last', 'month', '.']
[1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 0 1]
tensor([1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1])


In [47]:
ins = 17
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Stefano', 'Bordon', 'is', 'out', 'through', 'illness', 'and', 'Coste', 'said', 'he', 'had', 'dropped', 'back', 'row', 'Corrado', 'Covi', ',', 'who', 'had', 'been', 'recalled', 'for', 'the', 'England', 'game', 'after', 'five', 'years', 'out', 'of', 'the', 'national', 'team', '.']
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 1]
tensor([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 1, 1, 1, 1, 1, 1, 0, 0, 1])


In [48]:
ins = 18
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Cuttitta', 'announced', 'his', 'retirement', 'after', 'the', '1995', 'World', 'Cup', ',', 'where', 'he', 'took', 'issue', 'with', 'being', 'dropped', 'from', 'the', 'Italy', 'side', 'that', 'faced', 'England', 'in', 'the', 'pool', 'stages', '.']
[1 1 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1]
tensor([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 1])


In [49]:
ins = 19
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['Coste', 'said', 'he', 'had', 'approached', 'the', 'player', 'two', 'months', 'ago', 'about', 'a', 'comeback', '.']
[1 1 1 1 1 1 0 1 0 1 1 0 0 1]
tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1])


In [50]:
ins = 20
print(incor_instances[ins]['tokens'])
print(incor_instances[ins]['chunk_tags'])
print(ops[ins])

['AL-AIN', ',', 'United', 'Arab', 'Emirates', '1996-12-06']
[1 1 1 0 0 0]
tensor([1, 1, 1, 0, 0, 1])
